server:
    port: ${PORT:8080}

spring:
    datasource:
        url: jdbc:postgresql://localhost:${PORT:5432}/${DB_NAME:postgres}?useSSL=true
        username: ${DB_USER:postgres}
        password: ${DB_PASS:postgres}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
