version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: manga-db
    restart: always
    environment:
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=manga-db
    ports:
      - 5432:5432